title: "Jordan's portfolio"
author:
  name: Jordan Martinetti
  email: jordan@jordanmartinetti.com
description: |
    Personal collection of professional and personal work, education, and training.
baseurl: "" # the subpath of your site, e.g. /blog

markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - '/README.md'
  - '*.sass'
plugins:
  - jekyll-feed
  - jekyll-seo-tag

show_excerpts: true

# Minima specific settings, which are only available from Minima 3.0 onward.
minima:
  # Minima skin selection.
  # Available skins are:
  # classic	           Default, light color scheme.
  # dark	             Dark variant of the classic skin.
  # auto	             Adaptive skin based on the default classic and dark skins.
  # solarized-light	   Light variant of solarized color scheme.
  # solarized-dark	   Dark variant of solarized color scheme.
  # solarized	         Adaptive skin for solarized color scheme skins.
  skin: auto
  
  # Minima date format.
  # The default value is "%b %d, %Y" (e.g. Nov 14, 2023) 
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #date_format: "%b-%d-%Y"

  # Generate social links in footer.
  social_links:
  - { platform: github,         user_url: "https://github.com/JordanMPDS" }