- name: "Microsoft Certified: Azure Fundamentals"
  to: 2023-12-22
  description: >
    This certification validates your foundational knowledge of cloud concepts in general and Azure in particular.
    As a recipient for this certification, you can describe Azure architectural components and Azure services, such as compute, networking, and storage,
    as well as features and tools to secure, govern, and administer Azure.

- name: "Disciplined Agile Scrum Master (DASM)"
  to: 2021-10-31
  description: >
    Disciplined Agile is a toolkit that focuses on the decisions one needs to consider,
    the options available, and the associated trade-offs.
    The Disciplined Agile Scrum Master credential holder has been formally
    evaluated on understanding the fundamentals of agile and lean approaches like
    Scrum, Agile Modeling, Extreme Programming, Kanban, Agile Data, SAFe and more,
    in a tailorable and scalable manner. They have learned how to implement the
    Disciplined Agile tool kit to choose their way of working.

- name: "Tableau Desktop Specialist"
  to: 2021-05-18
  description: >
    Earners of the Tableau Desktop Specialist title use their foundational
    knowledge of Tableau Desktop and data analytics to solve problems.
    They have demonstrated understanding of Tableau core concepts and terminology.
    Desktop Specialists are able to connect to, prepare, explore and analyze data,
    and share their insights.

- name: "Microsoft Certified: Power BI Data Analyst Associate"
  to: 2020-06-01
  description: >
    As a recipient for this certification, you are able to deliver actionable
    insights by working with available data and applying domain expertise.
    As a Power BI data analyst, you work closely with business stakeholders
    to identify business requirements.
    You collaborate with enterprise data analysts and data engineers to
    identify and scquire data.
